image:
  name: 231865567661.dkr.ecr.us-west-1.amazonaws.com/node-builder:stable
  aws: &aws-shared-prod
    access-key: $ANSARADA_SHARED_PRODUCTION_AWS_ACCESS_KEY_ID
    secret-key: $ANSARADA_SHARED_PRODUCTION_AWS_SECRET_ACCESS_KEY

pipelines:
  definitions:
    - image: &spa-deployer
        name: 231865567661.dkr.ecr.us-west-1.amazonaws.com/spa-deployer:stable
        aws: *aws-shared-prod

    - step: &lint
        name: Lint Check
        script:
          - /cicd/run --lint

    - step: &flow
        name: Flow Type Check
        script:
          - /cicd/run --flow

    - step: &test
        name: Unit Tests
        script:
          - /cicd/run --test

    - step: &build-dev1
        name: Build Runtime for Dev1
        script:
          - /cicd/run --environment Dev1
        artifacts:
          - dist/**

    - step: &build-staging
        name: Build Runtime for Staging
        script:
          - /cicd/run --environment Staging
        artifacts:
          - dist/**

    - step: &build-production
        name: Build Runtime for Production
        script:
          - /cicd/run --environment Production
        artifacts:
          - dist/**

    - step: &deploy-dev1
        name: Deploy Dev1
        image: *spa-deployer
        script:
          - /cicd/run --environment=Dev1

    - step: &deploy-staging
        name: Deploy Staging
        image: *spa-deployer
        script:
          - /cicd/run --environment=Staging

    - step: &deploy-production
        name: Deploy Production
        image: *spa-deployer
        script:
          - /cicd/run --environment=Production

    - step: &security-tester
        name: Security Tester
        image:
          name: 231865567661.dkr.ecr.us-west-1.amazonaws.com/security-tester:stable
          aws: *aws-shared-prod
        script:
          - /cicd/run

  branches:
    master:
      - parallel:
          - step: *lint
          - step: *flow
          - step: *test
          - step: *security-tester
      - step: *build-dev1
      - step: *deploy-dev1
      - step: *build-staging
      - step: *deploy-staging
      - step: *build-production
      - step:
          <<: *deploy-production
          trigger: manual

  default:
    - parallel:
        - step: *lint
        - step: *flow
        - step: *test
        - step: *build-dev1
        - step: *security-tester
    - step:
        <<: *deploy-dev1
        trigger: manual

  custom:
    deploy-to-dev1:
      - step: *build-dev1
      - step: *deploy-dev1
